name: Build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    branches: [ master, 'main', dev ]
    paths:
    - "src/**"
    - ".github/workflows/**"
  pull_request:
    branches: [ master, 'main', dev ]
    paths:
    - "src/**"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    #  with:
    #    vs-version: '[16.7,16.8)'
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Generate Build Number
      id: buildnumber
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}

    - name: Build
      run: msbuild AiForms.SettingsView.sln /restore -m -property:Configuration=Release -property:BUILD_BUILDNUMBER=${{steps.buildnumber.outputs.build_number}} -property:BUILD_SOURCEBRANCHNAME=${{github.ref}}

    - name: Post NuGet Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nuget-artifacts
        path: '**/*.nupkg'
    - name: Publish to MyGet
      if: ${{ github.ref == 'refs/heads/dev' }}
      run: dotnet nuget push **\*.nupkg --source https://www.myget.org/F/acrfeed/api/v3/index.json --api-key ${{secrets.MYGETAPIKEY}} --skip-duplicate

    - name: Publish to NuGet
      if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
      run: dotnet nuget push **\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGETAPIKEY}} --skip-duplicate